oof
rot_mat = cv2.getRotationMatrix2D(left_eye_center_float, angle, 1.0)
TypeError: Can't parse 'center'. Sequence item with index 0 has a wrong type

The error is caused by the fact that, left_eye_center_float variable is tuple of floats, but not a tuple of integers.

Here's how you can change the code to fix the error: